name = "Booger aids 7"
author = ""
version = "1.0.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48ea464d16097791a6a6edebff5fc6e5aad9ef177af38389f839984b6350d009"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
unsup = "1.2.5"
