name = "Booger aids 7"
author = ""
version = "1.0.48"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a79653eca39c242cf7d5b71bbbb288a5d0c1facdda953fad599febb04a393ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
unsup = "1.2.5"
